# Numpy
NumPy is the fundamental package for scientific computing in Python. It provides numerous methods for performing 
mathematical operations on array. Operations on numpy arrays are faster compared to python list.

## Data types in numpy
- np.int8
- np.int16
- np.int32
- np.int64
- np.uint8
- np.uint16
- np.uint32
- np.uint64
- np.intp
- np.uintp
- np.float32
- np.float64
- np.complex64
- np.complex128

In [1]:
import numpy as np
import time

In [2]:
a = [i for i in range(1,1000000)] #list with 1M element
t1 = time.time()
b = []
for v in a:
    b.append(2*v)
t2 = time.time()
print(f'a = {a[:10]}')
print(f'b = {b[:10]}')
print(f'time = {(t2-t1)*1000}ms')

c = np.array(a)
t3 = time.time()
d = c*2
t4 = time.time()
print(f'c = {c[:10]}')
print(f'd = {d[:10]}')
print(f'time = {(t4-t3)*1000}ms')

a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
b = [2, 4, 6, 8, 10, 12, 14, 16, 18, 20]
time = 131.06107711791992ms
c = [ 1  2  3  4  5  6  7  8  9 10]
d = [ 2  4  6  8 10 12 14 16 18 20]
time = 2.404928207397461ms


## Array creation
commonly used method for array creation
- np.array
- np.zeros
- np.ones
- np.eye
- np.random.randint
- np.arange
- np.linspace
- np.full

In [4]:
#np.array
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
np.ones((5,2),dtype='int8')

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]], dtype=int8)

In [9]:
np.eye(5,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [12]:
np.random.randint(low=1,high=3,size=(5,3))

array([[2, 1, 1],
       [2, 2, 2],
       [1, 1, 2],
       [1, 1, 2],
       [2, 1, 2]])

In [11]:
np.arange(start=1,stop=10,step=2)

array([1, 3, 5, 7, 9])

In [13]:
np.linspace(2,10,10)

array([ 2.        ,  2.88888889,  3.77777778,  4.66666667,  5.55555556,
        6.44444444,  7.33333333,  8.22222222,  9.11111111, 10.        ])

In [15]:
np.full((2,7),5)

array([[5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5]])

## Inspecting arrays
commonly used properties are : 
- ndarray.shape
- ndarray.size
- ndarray.dtype
- ndarray.ndim

In [16]:
a = np.random.randint(1,90,(5,9))

In [17]:
a

array([[28, 56, 78, 38, 10, 83, 23, 73, 79],
       [60, 37, 87, 70, 57, 88, 18, 73, 43],
       [18, 31, 14, 72, 73,  7, 47, 72, 87],
       [38, 62, 66, 18, 54, 35, 24, 24, 53],
       [44,  4, 57, 61, 65, 59, 31, 53, 60]])

In [18]:
a.shape

(5, 9)

In [20]:
a.size

45

In [21]:
a.dtype

dtype('int64')

In [22]:
a.ndim

2

In [31]:
b = np.random.randint(1,100,(3,5,6))

In [32]:
print(f'shape : {b.shape}')
print(f'size : {b.size}')
print(f'type : {b.dtype}')
print(f'no dimension : {b.ndim}')

shape : (3, 5, 6)
size : 90
type : int64
no dimension : 3


In [27]:
np.info(np.ndarray.ndim)

Number of array dimensions.

Examples
--------
>>> x = np.array([1, 2, 3])
>>> x.ndim
1
>>> y = np.zeros((2, 3, 4))
>>> y.ndim
3


## Basic operations 
- copy
- reshape
- hstack
- vstack
- transpose


In [33]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [34]:
b = a 
b

array([1, 2, 3])

In [35]:
b[0]=-1
print(a)
print(b)

[-1  2  3]
[-1  2  3]


In [37]:
a = np.array([5,6,6,7])
c = a.copy()
print(f'a = {a}')
print(f'c = {c}')

a = [5 6 6 7]
c = [5 6 6 7]


In [38]:
c[0]=10
print(f'a = {a}')
print(f'c = {c}')

a = [5 6 6 7]
c = [10  6  6  7]


### copy
<img src='images/copy.png' width='250px' heigth='250px'>

In [39]:
#reshape
a = np.random.randint(1,100,(5,3,2))
a

array([[[71,  6],
        [54, 19],
        [15, 12]],

       [[12, 35],
        [13, 52],
        [25, 92]],

       [[45, 19],
        [19, 22],
        [80, 45]],

       [[19, 81],
        [25, 29],
        [87, 85]],

       [[76, 19],
        [68, 15],
        [41, 50]]])

In [40]:
a = a.reshape((2,15))
a

array([[71,  6, 54, 19, 15, 12, 12, 35, 13, 52, 25, 92, 45, 19, 19],
       [22, 80, 45, 19, 81, 25, 29, 87, 85, 76, 19, 68, 15, 41, 50]])

In [43]:
b = np.arange(0,100).reshape(2,10,5)
b

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74],
        [75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94],
        [95, 96, 97, 98, 99]]])

In [44]:
b.shape

(2, 10, 5)

In [45]:
#hstack
a = np.array([1,2,3])
b = np.array([4,5,6])
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [46]:
#vstack
np.vstack((b,a))

array([[4, 5, 6],
       [1, 2, 3]])

<img src='images/hstack.png' width='300px' height='300px'> <img src='images/vstack.png' width='300px' height='300px'>

In [47]:
#transpose
a = np.random.randint(1,100,(4,3))
a

array([[ 9, 39, 45],
       [73, 99,  9],
       [52,  3, 50],
       [23, 41,  2]])

In [48]:
b = a.T
b

array([[ 9, 73, 52, 23],
       [39, 99,  3, 41],
       [45,  9, 50,  2]])

## Indexing
- subsetting
- slicing
- fancy indexing
- boolean indexing

__0 indexed array__
<img src='images/array.png' width='250px' height='50px'>

In [49]:
a = np.array([88,19,46,74,94])
a

array([88, 19, 46, 74, 94])

In [51]:
a[1]

19

__indexing__
<img src='images/indexing.png' width='200px' height='200px'>

In [52]:
a = np.random.randint(1,100,(5,5))
a

array([[17, 55, 94, 36, 79],
       [14, 76, 16, 74, 38],
       [54, 31, 10, 98, 69],
       [89, 17,  6, 80, 12],
       [75, 38, 64,  3, 74]])

In [55]:
a[2,3]

98

In [56]:
a[0:3,2:]

array([[94, 36, 79],
       [16, 74, 38],
       [10, 98, 69]])

In [57]:
a[1:3,1:4]

array([[76, 16, 74],
       [31, 10, 98]])

__slicing__
<img src='images/slicing.png' width='200px' height='200px'>

In [59]:
b = np.random.randint(1,200,(7,9))
b

array([[199,  25, 156, 128,  13, 126, 146, 178, 159],
       [108,  55, 195, 180,  65,  77, 111,   7,  52],
       [178, 189, 112,  91, 115,  25,   5, 140, 128],
       [134,  75,  45, 152, 113,  73,  83,  41,  26],
       [ 32,  99,  89,  73,  65,  45, 175, 164, 141],
       [ 13,  73,  56, 109,  70, 141, 162, 101,  45],
       [143, 168,  75,  21, 198,  58, 161, 188,  28]])

In [62]:
b[[2,5],[1,3]]

array([189, 109])

In [64]:
c = b<50
c

array([[False,  True, False, False,  True, False, False, False, False],
       [False, False, False, False, False, False, False,  True, False],
       [False, False, False, False, False,  True,  True, False, False],
       [False, False,  True, False, False, False, False,  True,  True],
       [ True, False, False, False, False,  True, False, False, False],
       [ True, False, False, False, False, False, False, False,  True],
       [False, False, False,  True, False, False, False, False,  True]])

In [65]:
b[c]

array([25, 13,  7, 25,  5, 45, 41, 26, 32, 45, 13, 45, 21, 28])

## element-wise operation
- +
- -
- *
- %
- \>
- <

etc.

<img src='images/element-wise.png' width='400px' height='400px'>

In [70]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[32,3,5],[4,56,6]])
a>b

array([[False, False, False],
       [False, False, False]])

## Broadcasting
<img src='images/broadcasting.png' width='500px' height='400px'>

In [74]:
a = np.arange(0,4)
print(a)
b = np.array([1])
a+b

[0 1 2 3]


array([1, 2, 3, 4])

## Basic math
- np.power
- np.exp
- np.log
- np.sin
- np.cos
- np.sum
- np.min
- np.max
- np.median
- np.std
- np.sqrt

so on....

In [75]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [76]:
np.power(a,2)

array([1, 4, 9])

In [77]:
np.exp(a)#e^a[i]

array([ 2.71828183,  7.3890561 , 20.08553692])

## Linear algebra
- np.matmul

In [ ]:
#a , b
# a * b ->matrix multiplication
# col(a)=row(b) 

In [78]:
a = np.random.randint(1,100,(3,2))
b = np.random.randint(1,100,(2,5))
print(a)
print(b)

[[46 88]
 [63 18]
 [91 57]]
[[85  1 24 91 49]
 [76 13 35 46 97]]


In [79]:
np.matmul(a,b)

array([[10598,  1190,  4184,  8234, 10790],
       [ 6723,   297,  2142,  6561,  4833],
       [12067,   832,  4179, 10903,  9988]])

In [80]:
np.info(np.matmul)

matmul(x1, x2, /, out=None, *, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Matrix product of two arrays.

Parameters
----------
x1, x2 : array_like
    Input arrays, scalars not allowed.
out : ndarray, optional
    A location into which the result is stored. If provided, it must have
    a shape that matches the signature `(n,k),(k,m)->(n,m)`. If not
    provided or None, a freshly-allocated array is returned.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

    .. versionadded:: 1.16
       Now handles ufunc kwargs

Returns
-------
y : ndarray
    The matrix product of the inputs.
    This is a scalar only when both x1, x2 are 1-d vectors.

Raises
------
ValueError
    If the last dimension of `a` is not the same size as
    the second-to-last dimension of `b`.

    If a scalar value is passed in.

See Also
--------
vdot : Complex-conjugating dot product.
tensordot : Sum products over arbitrary axes.
einsu


## References
1. [numpy docs](https://numpy.org/doc/1.19/)
2. [numpy basics](https://www.sharpsightlabs.com/blog/numpy-array-python/)
3. [Broadcasting](https://numpy.org/doc/stable/user/basics.broadcasting.html)
4. [linear Algebra numpy](https://numpy.org/doc/stable/reference/routines.linalg.html)
4. image sources
    1. [broadcasting](https://scipy-lectures.org/intro/numpy/operations.html#broadcasting)
    2. [indexing and slicing](https://www.sharpsightlabs.com/blog/numpy-array-python/)
